# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
import numpy as np
array1 = np.arange(0,10)
array2 = array1.reshape(2,5)
print(f"1D-Array:\n {array1}\n 2D-Array:\n {array2}")


1D-Array:
 [0 1 2 3 4 5 6 7 8 9]
 2D-Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [32]:
import numpy as np
array1 = np.arange(0,10).reshape(2,5)
array2 = np.ones(10,dtype =int).reshape(2,5)
print(f"1D-Array:\n {array1}\n 2D-Array:\n {array2}")
np.vstack((array1,array2))
# stack_array = np.vstack((array1,array2))
# print(f"Stack_Array:\n {stack_array}")

1D-Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
 2D-Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [33]:
import numpy as np
array1 = np.arange(0,10).reshape(2,5)
array2 = np.ones(10,dtype =int).reshape(2,5)
print(f"1D-Array:\n {array1}\n 2D-Array:\n {array2}")
np.hstack((array1,array2))
# stack_array = np.vstack((array1,array2))
# print(f"Stack_Array:\n {stack_array}")

1D-Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
 2D-Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [52]:
import numpy as np
arr1 = np.arange(10).reshape(2,5)
print(f"{arr1.ndim}-Dimension Array :\n{arr1}")
arr2 = arr1.flatten()
# print(f"{arr2.ndim}-Dimension Array :\n{arr2}")
arr2

2-Dimension Array :
[[0 1 2 3 4]
 [5 6 7 8 9]]
1-Dimension Array :
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [43]:
import numpy as np
arr1 = np.arange(15).reshape(5,1,3)
print(f"{arr1.ndim}-Dimension Array :\n{arr1}")
flatten_array = arr1.flatten()
# print(f"{flatten_array.ndim}-Dimension Array :\n{flatten_array}")
flatten_array

3-Dimension Array :
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]

 [[12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [63]:
import numpy as np
arr1 = np.arange(15)
print(f"{arr1.ndim}-Dimension Array :\n{arr1}")
arr2 = arr1.reshape(-1,3)
# print(f"{arr2.ndim}-Dimension Array :\n{arr2}")
arr2
# arr2.ndim

1-Dimension Array :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [69]:
import numpy as np
arr1 = np.arange(25).reshape(5,5)
arr2 = np.square(arr1)
arr2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [80]:
import numpy as np
arr1 = np.arange(30).reshape(5,6)
arr2=arr1.mean()
print(f"5x6 Array:\n {arr1}\n mean: {arr2}")

# arr2.mean()

5x6 Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
 mean: 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [86]:
import numpy as np
arr1 = np.arange(30).reshape(5,6)
# arr2=arr1.std()
arr2=np.std(arr1)
print(f" Standard Deviation: {arr2}")
# print(f"5x6 Array:\n {arr1}\n Standard Deviation: {arr2}")


 Standard Deviation: 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [84]:
import numpy as np
arr1 = np.arange(30).reshape(5,6)
# arr2=arr1.median()
arr2=np.median(arr1)
print(f" Median: {arr2}")

 Median: 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [89]:
import numpy as np
arr1 = np.arange(30).reshape(5,6)
# arr2=arr1.transpose()
arr2=np.transpose(arr1)
print(f"5x6 Array:\n {arr1}\nTranspose:\n {arr2}")
# print(f"Transpose: {arr2}")



5x6 Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [94]:
import numpy as np
arr1 = np.arange(16).reshape(4,4)
# arr2=arr1.diagonal()
arr2=np.diagonal(arr1)
diag = np.sum(arr2)
print(f"5x6 Array:\n {arr1}\ndiagonal:\n {arr2}\nSum of Diagonal Elements:\n {diag}")

5x6 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
diagonal:
 [ 0  5 10 15]
Sum of Diagonal Elements:
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [99]:
import numpy as np
arr1 = np.arange(16).reshape(4,4)
# determinat=arr1.linalg.det()
determinat =np.linalg.det((arr1))
print(f"5x6 Array:\n {arr1}\nDeterminat:\n {determinat}")
# print(f"5x6 Array:\n {arr1}\nDeterminat:\n {determinat}\nSum of Diagonal Elements:\n {diag}")

5x6 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Determinat:
 -2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [105]:
import numpy as np
data = np.array([1,5,3,4,8,50,3,6,95,3,6,44,89])
# print(np.percentile(data,5))
# print(np.percentile(data,95))
a=np.percentile(data,5)
b=np.percentile(data,95)
print(f"5th Percentile: {a}\n59th Percentile: {b}")

5th Percentile: 2.2
59th Percentile: 91.39999999999999


## Question:15

### How to find if a given array has any null values?

In [1]:
import numpy as np
data = np.array([1,5,np.nan,50,6,95,np.nan,6,44,0,np.nan,np.nan])
find_null = np.isnan(data)
find_null

array([False, False,  True, False, False, False,  True, False, False,
       False,  True,  True])