# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [8]:
np.zeros(10)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [17]:
arr1 = np.arange(10,49)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [15]:
arr1.shape

(39,)

5. Print the type of the previous array in question 3

In [21]:
arr1.dtype
# type(arr1)

dtype('int32')

6. Print the numpy version and the configuration


In [3]:
#Print the numpy version and the configuration
# import numpy as np
# print(numpy.__version__)
# print(np.show_config())


print(f"Version:{np.__version__} and Configuration:{np.__config__}")



Version:1.18.1 and Configuration:<module 'numpy.__config__' from 'C:\\Users\\Malik\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


7. Print the dimension of the array in question 3


In [27]:
arr1.ndim

1

8. Create a boolean array with all the True values

In [7]:
import numpy as np
boolen_Array = np.ones((4,3),dtype =bool)
boolen_Array

# arr1.all()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [13]:
import numpy as np
arr_2d = np.array([[1,3,4,9,10],[12,3,6,9,8]])
arr_2d


# arr_2d = np.array([[1,3,5,7,9],[2,4,6,8]])
# # arr_2d = np.array([[1,3,5,7,9],[2,4,6,8]],ndmin=2)
# arr_2d



array([[ 1,  3,  4,  9, 10],
       [12,  3,  6,  9,  8]])

10. Create a three dimensional array



In [14]:
import numpy as np
arr_3d = np.array([[[1,3,5,6],[9,4,6,5],[2,7,3,4]]])
arr_3d


# arr_3d = np.array([3,6,9,15,21],ndmin=3)
# arr_3d.ndim

array([[[1, 3, 5, 6],
        [9, 4, 6, 5],
        [2, 7, 3, 4]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [15]:
import numpy as np
vector = np.arange(1,20)
print(f"simple vector: {vector}")
print(f"Reverse vector: {vector[::-1]}")

# import numpy as np
# x= np.array([1,25,33,44,50])
# x[::-1]

simple vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse vector: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [16]:
import numpy as np
x= np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [64]:
import numpy as np
x= np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [75]:
arr = np.array([1, 2, 3, 4, 5],dtype=float) 
arr


array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [79]:
import numpy as np
arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

    
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [83]:
import numpy as np
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [21]:
arr = np.arange(0,9)
arr[1::2]
# arr[arr % 2 != 0]

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [91]:
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr = np.arange(10)
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [111]:
arr = np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [28]:
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
np.where(arr2d==5,12,arr2d)



array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [43]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# arr3d[1:-1]=64
# arr3d[0]=64
arr3d[0:1,:2]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [18]:
import numpy as np
array1 = np.arange(9)
array2=np.reshape(array1,(3,3))
print(array2)
print(f"first 1st 1-D array: {array2[0]}")

# addr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
# print (addr2D)
# print(f"first 1st 1-D array: {addr2D[0][0:5]}")


[[0 1 2]
 [3 4 5]
 [6 7 8]]
first 1st 1-D array: [0 1 2]
[[0 1 2 3 4]
 [5 6 7 8 9]]
first 1st 1-D array: [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [23]:
import numpy as np
array1 = np.arange(10)
# array2 = np.reshape(array1,ndmin=2)
# arr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
array2=np.reshape(array1,(2,5))
print(array2)
print(f"2nd value from 2nd 1-D array: {array2[1][1]}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
2nd value from 2nd 1-D array: 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [6]:
import numpy as np
arr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
print(arr2D)
print(f"the third column but only the first two rows: {arr2D[:3,2]}")
# array1 = np.arange(10)
# array2=np.reshape(array1,(2,5))
# array2

[[0 1 2 3 4]
 [5 6 7 8 9]]
the third column but only the first two rows: [2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
import numpy as np
x = np.random.randint((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
# print(max(x))
# print(min(x))

Original Array:
[9 7]
Minimum and Maximum Values:
9
7


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [2]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Array1: ",a)
print("Array2: ",b)
print(np.intersect1d(a, b))

Array1:  [1 2 3 2 3 4 3 4 5 6]
Array2:  [ 7  2 10  2  7  4  9  4  9  8]
[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [3]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Array1: ",a)
print("Array2: ",b)
print(np.where(a==b))

Array1:  [1 2 3 2 3 4 3 4 5 6]
Array2:  [ 7  2 10  2  7  4  9  4  9  8]
(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [24]:
import numpy as np
import random 
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(data[names !='Will'])   
print(names[names !='Will'])
print([names !='Will'])
# Method-2
# x= names[names !='Will']   #....>['Bob' 'Joe' 'Bob' 'Joe' 'Joe']
# x= [names !='Will']   #....>[array([ True,  True, False,  True, False,  True,  True])]
# print(x)
# y = data[x]
# print(y)



[[ 1.03143797  1.83920226  1.98308729 -0.22790241]
 [ 0.72043326 -0.38442998 -0.81822059  1.19197643]
 [ 0.41436824 -1.06346438 -1.32175919 -0.32662531]
 [ 0.96474778  0.97134511  0.68218025 -0.80563457]
 [-0.73011177 -1.30488212 -0.3661398  -0.68082051]]
['Bob' 'Joe' 'Bob' 'Joe' 'Joe']
[array([ True,  True, False,  True, False,  True,  True])]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [25]:
import numpy as np
import random 
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print(data[names !='Will'],data[names !='Joe'])   
print(names[names !='Will'],names[names !='Joe']) 
print([names !='Will'],[names !='Joe']) 

[[ 0.43702964 -0.4039532   0.19835154 -0.7178615 ]
 [-0.29240694 -1.67198173  1.22207379 -1.00458612]
 [-1.58746737 -0.54340258  0.5712983  -1.78245124]
 [ 1.47069588 -1.15159753  0.32143063 -1.74493892]
 [-0.6288591  -0.10061889  0.32875829 -1.30725985]] [[ 0.43702964 -0.4039532   0.19835154 -0.7178615 ]
 [-1.46688051 -0.30018103 -1.7444182  -0.48833999]
 [-1.58746737 -0.54340258  0.5712983  -1.78245124]
 [-1.99471881  0.68728176 -1.4151275   0.07019204]]
['Bob' 'Joe' 'Bob' 'Joe' 'Joe'] ['Bob' 'Will' 'Bob' 'Will']
[array([ True,  True, False,  True, False,  True,  True])] [array([ True, False,  True,  True,  True, False, False])]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [43]:
import numpy as np
import random 
my_array = np.arange(1,16).reshape(3,5)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")

print("Dimension of Array: ",arr.ndim)


# my_array = np.random.randint(low=5,high=10,size=(5,3)) + np.random.random((5,3))
# my_array = np.random.uniform(low=5,high=10,size=15)
# my_array = np.random.uniform(low=1,high=15,size=15)
# resh_array = my_array.reshape(5,3)
# print(resh_array)

2D array of shape 5x3 to contain decimal numbers :
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
Dimension of Array:  2


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [45]:
import numpy as np
import random 
my_array = np.arange(1,17).reshape(2,2,4)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")

print("Dimension of Array: ",arr.ndim)
print("Shape of Array: ",arr.shape)

# import numpy as np
# import random 

# my_array = np.random.randn(1,16).reshape(2,2,4)
# print(my_array)

2D array of shape 5x3 to contain decimal numbers :
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
Dimension of Array:  3
Shape of Array:  (2, 2, 4)


33. Swap axes of the array you created in Question 32

In [47]:
import numpy as np
import random 
my_array = np.arange(1,17).reshape(2,2,4)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")
print(f"Swap axes of the array you created in Question 32 :\n {arr.T}")
print("Dimension of Array: ",arr.ndim)
print("Shape of Array: ",arr.shape)

2D array of shape 5x3 to contain decimal numbers :
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
Swap axes of the array you created in Question 32 :
 [[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]
Dimension of Array:  3
Shape of Array:  (2, 2, 4)


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [53]:
import numpy as np
ran = np.arange(10)
squre_root = np.sqrt(ran)
x=np.where(squre_root<0.5,0,squre_root)
print(f"square root of every element in the array:\n {x}")

square root of every element in the array:
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [65]:
import numpy as np
a = np.random.randint(12)
b = np.random.randint(12)
# a= np.arange(1,13)
# b= np.arange(1,13)
arr_1 = np.array(a)
arr_2 = np.array(b)

# result_no=np.maximum(a,b)
result_array=np.maximum(arr_1,arr_2)
# print(f" values of A: {a}\n values of B: {b} \n Maximum Value: {result_no}")
print(f" values of A: {arr_1}\n values of B: {arr_2} \n Maximum Value: {result_array}")

 values of A: 8
 values of B: 3 
 Maximum Value: 8


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [73]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq  = np.unique(names)
print(f"unique names by using Unique Method: {uniq} ")
    
print(f"unique names by using Set : {set(names)} ")

unique names by using Unique Method: ['Bob' 'Joe' 'Will'] 
unique names by using Set : {'Bob', 'Will', 'Joe'} 


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [34]:
# Method1
import numpy as np
test_list = np.array([1,2,3,4,5])
remove_list= np.array([5,6,7,8,9])

print(test_list!=remove_list)
print('\n',np.setdiff1d(test_list,remove_list))


# Method2
# '''
# test_list = list(np.array([1,2,3,4,5]))
# remove_list= list(np.array([5,6,7,8,9]))
# for i in remove_list:
#     try:
#         test_list.remove(i)
#     except ValueError:
#         pass
# '''
# Method3
# '''
# set1 = set(test_list)
# set2 = set(remove_list)
# res = list(set1 - set2)
# '''
# Method4

# res = [i for i in test_list if i not in remove_list]

# print ("The list after performing remove operation is : " + str(res))




[ True  True  True  True  True]

 [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [65]:
import numpy as np

print("Printing Original array")

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

print ("sampleArray:\n",sampleArray)

print("Array after deleting column 2 on axis 1")

deleteArray = np.delete(sampleArray , 1, axis = 1) 

print ("DeleteArray:\n",deleteArray)

newColumn = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")

insertArray = np.insert(deleteArray , 1, newColumn, axis = 1) 

print ("InsertArray:\n",insertArray)

Printing Original array
sampleArray:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
DeleteArray:
 [[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
InsertArray:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [69]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_prodct = np.dot(x,y)
print(f"Dot Product of the two matrix:\n {dot_prodct}")

Dot Product of the two matrix:
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [83]:
from numpy import random

x = random.randint(20)
cum_sum = np.cumsum(x)
print("random numbers:",x)
cum_sum

random numbers: 19


array([19], dtype=int32)